apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nodejs-app-deployment
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: test-nodejs-app
  replicas: 1
  template:
    metadata:
      labels:
        app: test-nodejs-app
    spec:
      containers:
      - name: test-app
        image: harbor.dorn.gorke.ml/nodejs/sample-app:v0.2.4
        env:
        - name: var1
          value: "Demo-var1"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test-nodejs-app
  namespace: test-app
  labels:
    app: test-nodejs-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-nodejs-app
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nodejs-app
  namespace: test-app
  labels:
    app: test-nodejs-app
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
  - host: test-nodejs-app.tanzu
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
           name: test-nodejs-app
           port:
             number: 80
